version: "3"
services:
  wiki:
    image: 057062899615.dkr.ecr.eu-central-1.amazonaws.com/dev-wikijs:latest
    environment:
      DB_TYPE: postgres
      DB_HOST: gibobs-dev.cl0dx0kdgakl.eu-central-1.rds.amazonaws.com
      DB_PORT: 25061
      DB_USER: root
      DB_PASS: eApvyNXaajyFqFSWTL6Y5U5TeFwD2q
      DB_NAME: wiki2
      DB_SSL: true
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3443"

volumes:
  db-data:
